[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | upper_first | trim }}{% if commit.remote.username %} - @{{ commit.remote.username }}{% elif commit.author.name %} - **{{ commit.author.name }}**{% endif %}{% if commit.breaking %} [**breaking**]{% endif %}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
filter_unconventional = false
conventional_commits = true
filter_commits = false
