[changelog]
body = """
{% if release.version %}
    ## [{{ release.version | trim_start_matches(pat="v") }}] - {{ release.timestamp | date(format="%Y-%m-%d") }}
{% else %}
    ## [unreleased]
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{{ commit.description | upper_first | trim }}{% if commit.remote.username %} by [@{{ commit.remote.username }}](https://github.com/{{ commit.remote.username }}){% elif commit.author.name %} by **{{ commit.author.name }}**{% endif %}{% if commit.breaking %} [**breaking**]{% endif %}
{% endfor %}
{% endfor %}

{% set returning = github.contributors | filter(attribute="is_first_time", value=false) | unique(attribute="username") %}
{% set newcomers = github.contributors | filter(attribute="is_first_time", value=true) %}

{% if returning %}
### Contributors
{% for contributor in returning %}
- [@{{ contributor.username }}](https://github.com/{{ contributor.username }})
{% endfor %}
{% endif %}

{% if newcomers %}
### New Contributors
{% for contributor in newcomers %}
- [@{{ contributor.username }}](https://github.com/{{ contributor.username }}) made their first contribution in [#{{ contributor.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ contributor.pr_number }})
{% endfor %}
{% endif %}

{% if release.previous.version %}
**Full Changelog**: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ release.previous.version }}...{{ release.version }}
{% else %}
**Full Changelog**: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commits/{{ release.version }}
{% endif %}
"""
trim = true

[git]
filter_unconventional = false
conventional_commits = true
filter_commits = false
commit_parsers = [
  { message = "^Merge pull request", skip = true },
  { message = "^Merge branch", skip = true },
  { message = "^refactor\\(clippy\\)", skip = true },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
  { message = "^feat", group = "<!-- 0 -->🚀 Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
  { message = "^doc", group = "<!-- 3 -->📚 Documentation" },
  { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
  { message = "^style", group = "<!-- 5 -->🎨 Styling" },
  { message = "^test", group = "<!-- 6 -->🧪 Testing" },
  { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 8 -->🛡️ Security" },
  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },
  { message = ".*", group = "<!-- 10 -->💼 Other" },
]

[remote.github]
owner = "zeborg"
repo = "kubekosh"